language: c

os: linux
dist: trusty
group: stable

addons:
  apt:
    packages:
      - libstdc++6
      - gcc-4.9-base

before_install:
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - wget $(curl -s https://api.github.com/repos/Steveice10/bannertool/releases | grep browser_download_url | grep '.zip' | head -n 1 | cut -d '"' -f 4) -O bannertool.zip
  - unzip bannertool.zip -d ./bannertool/
  - mkdir working
  - cp ./bannertool/linux-$(arch)/bannertool ./working/
  - wget $(curl -s https://api.github.com/repos/profi200/Project_CTR/releases | grep browser_download_url | grep '.zip' | head -n 1 | cut -d '"' -f 4) -O Project_CTR.zip
  - unzip Project_CTR.zip -d ./projectctr/
  - cp ./projectctr/Linux_$(arch)/makerom ./working/
  - sudo dpkg -i devkitpro-pacman.deb

install:
  - sudo dkp-pacman -Sy
  - sudo dkp-pacman -S 3ds-dev --noconfirm
  - export PATH=$(pwd)/working:$PATH
  - git clone https://github.com/Steveice10/buildtools
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get -y install gcc-4.9
  - sudo apt-get -y upgrade libstdc++6

before_script:
  - source /etc/profile.d/devkit-env.sh

script:
  - make
